name: Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.27.0-rc.1'
          cache: true

      - name: Install Tree-sitter CLI binary
        run: |
          curl -sL https://github.com/tree-sitter/tree-sitter/releases/latest/download/tree-sitter-linux-x64.gz | gunzip > tree-sitter
          chmod +x tree-sitter
          sudo mv tree-sitter /usr/local/bin/

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: make test

      - name: Build
        run: go build -v ./...
